# Site settings
title: IPCAI 2019
email: chene@robarts.ca
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.ipcai2019.org" 

twitter_username:
github_username:

# Build settings
markdown: kramdown
